rule all:
    input:
        expand(
            "portcullis/filter/{sp}.pass.junctions.tab",
            sp=["bcte", "cmer", "dden", "ecau", "ecun", "iint", "mosp", "mrub", "tamp",
                "lox1", "dcos", "rlon", "sp10", "ssta", "amp2", "epi1", "epi2", "did1", "dim2", "asch", "avis",
            ],
        )

rule portcullis_filter:
    input:
        tab="portcullis/junc/{sp}.junctions.tab",
    output:
        filt="portcullis/filter/{sp}.pass.junctions.tab",
    conda: "envs/portcullis.yml"
    params:
        prep_dir="portcullis/prep.{sp}",
        prefix="portcullis/filter/{sp}",
    log: "logs/portcullis_filter.{sp}.log"
    shell:
        """
        portcullis filter -o {params.prefix} {params.prep_dir} {input.tab} &> {log}
        """

rule portcullis_junc:
    input:
        ref="portcullis/prep.{sp}/portcullis.genome.fa",
        sort="portcullis/prep.{sp}/portcullis.sorted.alignments.bam",
    output:
        tab="portcullis/junc/{sp}.junctions.tab",
    conda: "envs/portcullis.yml"
    threads: 24
    log: "logs/portcullis_junc.{sp}.log"
    params:
        prep_dir="portcullis/prep.{sp}",
        prefix="portcullis/junc/{sp}",
    shell:
        """
        portcullis junc --threads {threads} -o {params.prefix} --intron_gff {params.prep_dir} &> {log}
        """

rule portcullis_prep:
    input:
        ref=lambda wildcards: config[wildcards.sp]["ref"],
        sort="mapping/{sp}.hisat2.sort.bam",
    output:
        ref="portcullis/prep.{sp}/portcullis.genome.fa",
        sort="portcullis/prep.{sp}/portcullis.sorted.alignments.bam",
    conda: "envs/portcullis.yml"
    threads: 1
    log: "logs/portcullis_prep.{sp}.log"
    params:
        outdir="portcullis/prep.{sp}"
    shell:
        """
        portcullis prep -o {params.outdir} {input.ref} {input.sort} &> {log}
        """

rule sort_index_mapping:
    input:
        "mapping/{sp}.hisat2.bam",
    output:
        sort="mapping/{sp}.hisat2.sort.bam",
        index="mapping/{sp}.hisat2.sort.bam.bai",
    threads: 4
    conda: "envs/samtools.yml"
    shell:
        """
        samtools sort --threads {threads} -o {output.sort} --write-index {input};
        samtools index {output.sort};
        """

rule hisat_map:
    input:
        # hisat2="hisat2/hisat2",
        index="mapping/{sp}.1.ht2",
        fwd=lambda wildcards: config[wildcards.sp]["fwd"],
        rev=lambda wildcards: config[wildcards.sp]["rev"],
    output:
        bam=temp("mapping/{sp}.hisat2.bam"),
        summary="mapping/{sp}.hisat2.summary",
    params:
        prefix=lambda wildcards: "mapping/" + wildcards.sp,
        infwd=lambda wildcards, input: ",".join(input.fwd),
        inrev=lambda wildcards, input: ",".join(input.rev),
    threads: 24
    conda: "envs/samtools.yml"
    log: "logs/hisat_map.{sp}.log"
    shell:
        """
        hisat2/hisat2 --threads {threads} --min-intronlen 9 -x {params.prefix} -1 {params.infwd} -2 {params.inrev} --summary-file {output.summary} | samtools view -b --fast -o {output.bam} &> {log}
        """

rule hisat_build:
    input:
        ref=lambda wildcards: config[wildcards.sp]["ref"],
        # hisat2_build="hisat2/hisat2-build",
    output:
        "mapping/{sp}.1.ht2"
    params:
        seed=54321,
        prefix=lambda wildcards: "mapping/" + wildcards.sp,
    log:
        "logs/hisat_build.{sp}.log"
    shell:
        """
        hisat2/hisat2-build --seed {params.seed} {input.ref} {params.prefix} &> {log}
        """


rule compile_hisat2:
    output:
        hisat2="hisat2/hisat2",
        hisat2_build="hisat2/hisat2-build",
    shell:
        """
        cd hisat2; make
        """
